_target_: torch_mist.estimators.hybrid.reweighed_hybrid
_partial_: true
discriminative_estimator: nwj
generative_estimator: doe
discriminative_params:
  neg_samples: ${neg_samples}
generative_params:
  marginal_transform_name: ${params.marginal_transform_name}
  conditional_transform_name: ${params.conditional_transform_name}